### ISSUE TITLE
Makefile:160: recipe for target 'all' failed

### ISSUE THREAD

**Issue by mintisan** [jetsonhacks/buildOpenCVTX2#1]
I installed Jetpack 3.0, and `buildOpenCV.sh` , but encouter the `Makefile:160: recipe for target 'all' failed` error. I don't if I lost some configuration or something else?

```
➜  buildOpenCVTX2 git:(master) ./buildOpenCV.sh
.................................................................
[ 11%] Linking CXX shared library ../../lib/libopencv_ml.so
[ 11%] Linking CXX shared library ../../lib/libopencv_cudaarithm.so
[ 11%] Linking CXX shared library ../../lib/libopencv_imgproc.so
[ 11%] Built target opencv_flann
[ 12%] Built target opencv_ml
[ 16%] Built target opencv_imgproc
[ 16%] Linking CXX shared library ../../lib/libopencv_cudawarping.so
[ 16%] Linking CXX shared library ../../lib/libopencv_video.so
[ 16%] Linking CXX shared library ../../lib/libopencv_imgcodecs.so
[ 19%] Built target opencv_cudaarithm
[ 19%] Built target opencv_video
[ 20%] Built target opencv_imgcodecs
[ 20%] Linking CXX shared library ../../lib/libopencv_cudabgsegm.so
[ 20%] Linking CXX shared library ../../lib/libopencv_cudafilters.so
[ 20%] Linking CXX shared library ../../lib/libopencv_shape.so
[ 20%] Built target opencv_cudawarping
[ 20%] Linking CXX shared library ../../lib/libopencv_videoio.so
CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.32sc4.cu.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
modules/cudafilters/CMakeFiles/opencv_cudafilters.dir/build.make:6772: recipe for target 'lib/libopencv_cudafilters.so.3.2.0' failed
make[2]: *** [lib/libopencv_cudafilters.so.3.2.0] Error 1
CMakeFiles/Makefile2:2525: recipe for target 'modules/cudafilters/CMakeFiles/opencv_cudafilters.dir/all' failed
make[1]: *** [modules/cudafilters/CMakeFiles/opencv_cudafilters.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 20%] Built target opencv_cudabgsegm
[ 20%] Built target opencv_shape
[ 21%] Built target opencv_videoio
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
➜  buildOpenCVTX2 git:(master) 

````

**Comment by jetsonhacks** [comment]
Looks like you had issues building cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.32sc4.cu.o
Did you try deleting it and rebuilding?

**Comment by jetsetgo** [comment]
Hi..I was able to successfully execute : /buildOpenCV.sh.
When I try executing : 
$ cd ~/opencv/build
$ sudo make install

I get following error:
.........
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_frontalface_alt2.xml
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_fullbody.xml
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_frontalface_alt_tree.xml
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_russian_plate_number.xml
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_smile.xml
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_righteye_2splits.xml
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_frontalface_alt.xml
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_eye_tree_eyeglasses.xml
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_frontalcatface.xml
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_lefteye_2splits.xml
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_licence_plate_rus_16stages.xml
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_lowerbody.xml
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_profileface.xml
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_frontalface_default.xml
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_frontalcatface_extended.xml
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_eye.xml
-- Up-to-date: /usr/share/OpenCV/haarcascades/haarcascade_upperbody.xml
-- Up-to-date: /usr/share/OpenCV/lbpcascades/lbpcascade_profileface.xml
-- Up-to-date: /usr/share/OpenCV/lbpcascades/lbpcascade_frontalface.xml
-- Up-to-date: /usr/share/OpenCV/lbpcascades/lbpcascade_frontalcatface.xml
-- Up-to-date: /usr/share/OpenCV/lbpcascades/lbpcascade_silverware.xml
CMake Error at data/cmake_install.cmake:67 (file):
  file INSTALL cannot find "/home/nvidia/opencv_extra/testdata".
Call Stack (most recent call first):
  cmake_install.cmake:84 (include)
  


Makefile:116: recipe for target 'install' failed
make: *** [install] Error 1


Anything that I am missing?

**Comment by carriojazz** [comment]
In the file buildOpenCV.sh change line 67 to look like this:

-DOPENCV_TEST_DATA_PATH=../../opencv_extra/testdata \

This fixed this issue for me.

**Comment by eng-tech1993** [comment]
hi friends, sorry but can you explain how to change line 67 to -DOPENCV_TEST_DATA_PATH=../../opencv_extra/testdata \  

best regard ..
