### ISSUE TITLE
Updated version for Jetpack 3.2 with CUDA support

### ISSUE THREAD

**Issue by bcizmeci** [jetsonhacks/buildOpenCVTX2#10]
Hi,

It would be great if you are able to update the repository for Jetpack 3.2. 
Is it also possible to provide a simple example showing cuda working with OpenCV?

Thanks for your great support!
Cheers,
Burak

**Comment by Alro10** [comment]
Hi @bcizmeci,

Check my repository for Jetpack 3.2 

https://github.com/AlexanderRobles21/OpenCVTX2

Cheers!

**Comment by jetsonhacks** [comment]
Please see the latest release:
https://github.com/jetsonhacks/buildOpenCVTX2/tree/v2.0OpenCV3.4
