### ISSUE TITLE
How to configure environment variables

### ISSUE THREAD

**Issue by Programmerwyl** [jetsonhacks/buildOpenCVTX2#18]
Firstly ,thanks for your work
I have some question 
when I complete the script , is it necessary to configure the environment variables for opencv ？
Is there any way to tell if cuda is accelerating opencv ?
Thanks again

**Comment by jetsonhacks** [comment]
It's a standard OpenCV installation, you will need to configure it accordingly.

**Comment by Programmerwyl** [comment]
Hi @jetsonhacks  Thank you very much for your reply.
I don't really know how to configure it, can you tell me more about it
Thanks

**Comment by jetsonhacks** [comment]
It depends on what you are trying to accomplish. 
There are entire books written on the subject, for example: https://amzn.to/2M5bej6
For this script, there is an article and a video: https://www.jetsonhacks.com/2018/05/28/build-opencv-3-4-with-cuda-on-nvidia-jetson-tx2/

In a code repository such as this, typically people ask specific questions about issues they are having.
