### ISSUE TITLE
Installing OpenCV 3.3.0 with opencv-contrib, but got error during make

### ISSUE THREAD

**Issue by shakil10vr** [jetsonhacks/buildOpenCVTX2#3]
Hi, 
I installing opencv 3.3.0 on my raspberry pi 3, using the cmake with the following configure:
cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D INSTALL_C_EXAMPLES=OFF \
-D INSTALL_PYTHON_EXAMPLES=ON \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D WITH_V4L=ON \
-D INSTALL_CREATE_DISTRIB=ON \
-D ENABLE_NEON=ON \
-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
-D BUILD_EXAMPLES=ON ..

But ended up, with the following error

CMakeFiles/opencv_perf_imgproc.dir/__/imgproc/perf/opencl/perf_pyramid.cpp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
modules/world/CMakeFiles/opencv_perf_imgproc.dir/build.make:1033: recipe for target 'bin/opencv_perf_imgproc' failed
make[2]: *** [bin/opencv_perf_imgproc] Error 1
CMakeFiles/Makefile2:5038: recipe for target 'modules/world/CMakeFiles/opencv_perf_imgproc.dir/all' failed
make[1]: *** [modules/world/CMakeFiles/opencv_perf_imgproc.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jetsonhacks** [comment]
This repository is for building OpenCV on the NVIDIA Jetson TX2, not the Raspberry Pi.
