### ISSUE TITLE
camera open failed

### ISSUE THREAD

**Issue by ChristophTobler** [jetsonhacks/buildOpenCVTX2#4]
First of all: Thanks for having all this stuff open-source:+1:

I have a TX2 with the latest [JetPack 3.1](https://developer.nvidia.com/embedded/jetpack) (L4T 28.1) and have uninstalled the preinstalled OpenCV version (`sudo apt-get purge libopencv4tegra*`). After that I installed OpenCV again using your script. That all worked!
The gstreamer_view.cpp works as well.

But if I run `python cannyDetection.py` I get
```
camera open failed
```
Any ideas?

**Comment by jetsonhacks** [comment]
Usually I run it with:
$ ./cannyDetection.py
but that shouldn't make any difference.
Did you try it with sudo?

**Comment by ChristophTobler** [comment]
Works with `sudo ./cannyDetection.py` or `sudo python cannyDetection.py`. Thanks!
