### ISSUE TITLE
JetPack 3.2

### ISSUE THREAD

**Issue by logidelic** [jetsonhacks/buildOpenCVTX2#5]
Should this be working with JetPack 3.2 (i.e. L4T 28.2 RC)? When I try, it builds OpenCV without CUDA support...

**Comment by jetsonhacks** [comment]
The current script as of this writing is for L4T 28.1 as stated in the release notes. 

If read through the script, you will find:

-DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 \

I believe that L4T 28.2 RC uses CUDA 9. If that is the case, then the build system probably just defaults back to no GPU support. There may be other changes needed.

**Comment by logidelic** [comment]
Thanks for the response. I tried a few things, including changing the cuda dir, but I run into problems one way or the other. It looks like OpenCV simply does not yet support cuda 9.

I see [here](https://stackoverflow.com/a/46614298/1072039) that there are some possible workarounds, but I haven't tried myself... Would certainly be cool if buildOpenCVTX2 could automate it.

**Comment by jetsonhacks** [comment]
Updated version now available:
https://github.com/jetsonhacks/buildOpenCVTX2/releases/tag/v2.0OpenCV3.4
