### ISSUE TITLE
Enabling python3 doesn't work

### ISSUE THREAD

**Issue by kmonte** [jetsonhacks/buildOpenCVTX2#7]
I set     -DBUILD_opencv_python3=OFF \ to ON and then installed but I cannot import cv2 in a python3 environment.

**Comment by Alro10** [comment]
Hi! I add this line after # Python 2.7:

sudo apt-get install -y python3-dev python3-numpy python3-py python3-pytest -y 

It works for me.

You can check my repository for installing OpenCV on Ubuntu 16.04:

https://github.com/AlexanderRobles21/buildOpenCVUbuntu

**Comment by jetsonhacks** [comment]
Please see version 2.0 of this repository for an example with Python 3 support:
https://github.com/jetsonhacks/buildOpenCVTX2/releases/tag/v2.0OpenCV3.4
