### ISSUE TITLE
Opencv dnn doesnot use GPU

### ISSUE THREAD

**Issue by Mamta-B** [jetsonhacks/buildOpenCVTX2#8]
I m using the following to detect objects using SSD mobilenet (CAffe) on Jetson TX2 with opencv3.4.1 and Cuda 9.0

blob = cv2.dnn.blobFromImage(cv2.resize(frame, (300, 300)), 0.007843, (300, 300), 127.5)
net.setInput(blob)
detections = net.forward()

The tegrastats show no GPU usage at all. All the cores of the CPU are utilized properly, however GPU utilisation is zero.

How can I enable GPU usage on the Jetson for faster FPS on videos ?

Thanks

**Comment by jetsonhacks** [comment]
Are you using Python?

**Comment by jetsonhacks** [comment]
Are you linked against the OpenCV 3.4 libraries in Caffe? Without providing more information, it is difficult to diagnose your issue.
